# -*- coding: utf-8 -*-
"""HouseBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O4mytO_tiUK37awe8vNDJfeSwhd3B4rW
"""

# ── Install and Imports ─────────────────────────────────────────────────────────
!pip install gspread pandas python-dotenv gspread_dataframe

import os
import json
import pandas as pd
import gspread
from google.colab import drive

drive.mount('/content/drive')

os.environ["GOOGLE_SERVICE_ACCOUNT_JSON"] = "/content/drive/MyDrive/Documents/Projects/HouseBot/housebot_creds.json"
os.environ["OPENAI_API_KEY"] = "[...]" #<-- Input API key here

# ── Authenticate with Google Drive API using Service Account ──
import os
from google.oauth2.service_account import Credentials
from googleapiclient.discovery import build
import io
import pandas as pd

SERVICE_ACCOUNT_FILE = os.environ["GOOGLE_SERVICE_ACCOUNT_JSON"]
scopes = ["https://www.googleapis.com/auth/drive.readonly"]

creds = Credentials.from_service_account_file(SERVICE_ACCOUNT_FILE, scopes=scopes)
drive_service = build('drive', 'v3', credentials=creds)

# ── Function to load spreadsheet from Drive ──
def load_excel_from_drive(filename):
    # Find file by name
    results = drive_service.files().list(
        q=f"name='{filename}'",###<--------!
        fields="files(id, name)"
    ).execute()
    items = results.get('files', [])

    if not items:
        raise FileNotFoundError(f"Could not find file: {filename}")###,----!

    file_id = items[0]['id']
    request = drive_service.files().get_media(fileId=file_id)
    file = io.BytesIO(request.execute())

    # Load Excel data into pandas directly from memory
    return pd.read_excel(file, sheet_name=None)


# ── Environment Variables ───────────────────────────────────────────────────────
os.environ["GOOGLE_SERVICE_ACCOUNT_JSON"] = "/content/drive/My Drive/Documents/Projects/HouseBot/housebot_creds.json"
os.environ["SPREADSHEET_ID"]              = "1427pbk7sbY6TzhxNxlwimSTD93Vg3h9rvY0ARS3Tynk"
os.environ["TARGET_MONTH"]                = "2025-07"

# ── Helper: Read a Sheet into a DataFrame ────────────────────────────────────────
def read_sheet(sheet_name: str) -> pd.DataFrame:
    creds = Credentials.from_service_account_file(
        os.environ["GOOGLE_SERVICE_ACCOUNT_JSON"],
        scopes=[
            "https://www.googleapis.com/auth/spreadsheets.readonly",
            "https://www.googleapis.com/auth/drive.readonly",
        ],
    )
    client = gspread.authorize(creds)
    ws     = client.open_by_key(os.environ["SPREADSHEET_ID"]).worksheet(sheet_name)
    return pd.DataFrame(ws.get_all_records())


